basePath: /v1
consumes:
- application/json
definitions:
  filtro_log_request:
    properties:
      codigoResponsable:
        type: integer
      entornoApi:
        type: string
      fechaFin:
        type: string
      fechaInicio:
        type: string
      horaFin:
        type: string
      horaInicio:
        type: string
      nombreApi:
        type: string
      tipo_log:
        type: string
    required:
    - codigoResponsable
    - entornoApi
    - fechaFin
    - fechaInicio
    - horaFin
    - horaInicio
    - nombreApi
    - tipo_log
    type: object
info:
  description: Api mid para la obtención de logs de AWS
  title: auditoria_mid
  version: '1.0'
paths:
  /auditoria/:
    get:
      description: "Parameters\n----------\nNinguno\n\nReturns\n-------\nResponse\n\
        \    Respuesta con los logs consultados o error."
      operationId: get_document_get_all
      responses:
        '200':
          description: Success
        '206':
          description: Partial Content
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Server error
      summary: Consulta eventos de logs en AWS CloudWatch
      tags:
      - auditoria
  /auditoria/buscarLog:
    post:
      description: "Parameters\n----------\nrequest : json\n    Un JSON que contiene:\n\
        \    - fechaInicio (str): Fecha de inicio en formato aaaa-mm-dd\n    - horaInicio\
        \ (str): Hora de inicio en formato hh:mm\n    - fechaFin (str): Fecha de fin\
        \ en formato aaaa-mm-dd\n    - horaFin (str): Hora de fin en formato hh:mm\n\
        \    - tipo_log (str): Tipo de log (GET, POST, PUT, etc.)\n    - codigoResponsable\
        \ (int): Código del responsable\n    - rolResponsable (str): Rol del responsable\n\
        \nReturns\n-------\nResponse\n    Respuesta con los logs filtrados en formato\
        \ JSON."
      operationId: post_filter_logs
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/filtro_log_request'
      responses:
        '200':
          description: Success
        '206':
          description: Partial Content
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Server error
      summary: Filtra los logs de AWS con base en parámetros específicos
      tags:
      - auditoria
  /auditoria/buscarLogsFiltrados:
    get:
      description: Permite búsqueda incremental con paginación para mejor performance.
      operationId: get_filter_logs_paginated
      parameters:
      - description: Dirección IP
        in: query
        name: ip
        type: string
      - description: Endpoint específico
        in: query
        name: endpoint
        type: string
      - description: API específica
        in: query
        name: api
        type: string
      - description: Email del usuario responsable
        in: query
        name: codigoResponsable
        type: string
      - description: Método HTTP (GET, POST, PUT, DELETE)
        in: query
        name: tipo_log
        type: string
      - default: 10
        description: Registros por página
        in: query
        name: limit
        type: string
      - default: 1
        description: Número de página
        in: query
        name: page
        type: string
      - description: Hora de fin (HH:MM)
        in: query
        name: horaFin
        required: true
        type: string
      - description: Fecha de fin (YYYY-MM-DD)
        in: query
        name: fechaFin
        required: true
        type: string
      - description: Hora de inicio (HH:MM)
        in: query
        name: horaInicio
        required: true
        type: string
      - description: Fecha de inicio (YYYY-MM-DD)
        in: query
        name: fechaInicio
        required: true
        type: string
      - description: Entorno (SANDBOX, PRODUCTION, TEST)
        in: query
        name: entornoApi
        required: true
        type: string
      - description: 'Nombre del API (ej: polux_crud)'
        in: query
        name: nombreApi
        required: true
        type: string
      responses:
        '200':
          description: Success
        '400':
          description: Bad request
        '404':
          description: Not found
        '500':
          description: Server error
      summary: Filtra y pagina logs de AWS con base en parámetros en la URL
      tags:
      - auditoria
produces:
- application/json
responses:
  MaskError:
    description: When any error occurs on mask
  ParseError:
    description: When a mask can't be parsed
swagger: '2.0'
tags:
- description: Consulta logs de AWS
  name: auditoria
